testing pipeline

diff --git a/.github/workflows/Pipeline-frontend-to-DockerHub.yml b/.github/workflows/Pipeline-frontend-to-DockerHub.yml
--- a/.github/workflows/Pipeline-frontend-to-DockerHub.yml
+++ b/.github/workflows/Pipeline-frontend-to-DockerHub.yml
@@ -84,4 +84,14 @@ jobs:
       - name: List S3 Buckets
         run: aws s3 ls --region eu-central-1 --profile 048479317518_Student
 
-        ##
+      - name: SSH into EC2 instance
+        run: |
+          chmod 400 "SSH-Abschlussproject.pem"
+          echo "[$(date -u)] Starting SSH connection..."
+          ssh -v -i "SSH-Abschlussproject.pem" root@ec2-3-125-155-152.eu-central-1.compute.amazonaws.com
+          if [ $? -eq 0 ]; then
+          echo "[$(date -u)] SSH connection successful"
+          else
+          echo "[$(date -u)] Error: Failed to establish SSH connection"
+          exit 1
+          fi
