testing pipeline

diff --git a/.github/workflows/Pipeline-frontend-to-DockerHub.yml b/.github/workflows/Pipeline-frontend-to-DockerHub.yml
--- a/.github/workflows/Pipeline-frontend-to-DockerHub.yml
+++ b/.github/workflows/Pipeline-frontend-to-DockerHub.yml
@@ -34,6 +34,31 @@ jobs:
             exit 1
           fi
 
+      - name: Tag Docker image
+        run: |
+          echo "[$(date -u)] Tagging Docker image..."
+          docker tag aws2302/aws2302:latest "${{ secrets.DOCKERHUB_USERNAME }}/aws2302:latest"
+          if [ $? -eq 0 ]; then
+            echo "[$(date -u)] Tagged Docker image successfully"
+          else
+            echo "[$(date -u)] Error: Failed to tag Docker image"
+            exit 1
+          fi
+
+      - name: Push Docker image
+        run: |
+          echo "[$(date -u)] Pushing Docker image..."
+          docker push "${{ secrets.DOCKERHUB_USERNAME }}/aws2302:latest"
+          if [ $? -eq 0 ]; then
+            echo "[$(date -u)] Pushed Docker image successfully"
+          else
+            echo "[$(date -u)] Error: Failed to push Docker image"
+            exit 1
+          fi
+
+      - name: Task complete
+        run: echo "[$(date -u)] Task complete"
+
   aws-steps:
     runs-on: ubuntu-latest
     needs: build-and-push
